version: '3.5'

networks:
  database:
    name: mysql8_network
    driver: bridge
    internal: false

volumes:
  mysql:

services:
  db:
    image: mysql:8
    container_name: mysql_8
    command: --max_allowed_packet=134217728
    restart: always
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: "false"
    networks:
      - database
